import {
  DURABILITY_REQUIRED_CAPABILITIES,
  PROJECTION_REQUIRED_CAPABILITIES,
  SUBSCRIPTION_REQUIRED_CAPABILITIES,
  type CapabilityManifest,
  type DeadLetterRecord,
  type DeliveryAttempt,
  type DeliveryClaimResult,
  type DeliverySettlement,
  type DeliverySettlementResult,
  type DeliveryStateStore,
  type EventRecord,
  type OutboxClaim,
  type OutboxRecord,
  type OutboxStore,
  type PendingDeliveryRecord,
  type ProjectionCheckpointStore,
  type ProjectionFailureRecord,
  type ProjectionFailureStore,
  type RuntimeSubscription,
  type SubscriptionStore,
  type WorkerLease,
  type WorkerLeaseStore,
} from "@work-fabric/exchange-spi";
import {
  addUtcTimestampSeconds,
  parseUtcTimestamp,
} from "@work-fabric/exchange-spi";
import type { PostgresClient as PgClient, TenantSession as PgTenantSession } from "@work-fabric/adapter-postgres-common";

const manifest: CapabilityManifest = {
  profile: "exchange.runtime.v1",
  adapter: "postgres",
  capabilities: {
    ...Object.fromEntries([
      ...DURABILITY_REQUIRED_CAPABILITIES,
      ...PROJECTION_REQUIRED_CAPABILITIES,
      ...SUBSCRIPTION_REQUIRED_CAPABILITIES,
      "active_delivery_cas", "atomic_delivery_settlement", "idempotent_dead_letters",
    ].map((capability) => [capability, true])),
  },
};

function clone<T>(value: T): T { return structuredClone(value); }
function identity(value: unknown, label: string): void { if (typeof value !== "string" || value.trim() === "") throw new TypeError(`${label} must be non-empty`); }
function nonNegative(value: unknown, label: string): void { if (!Number.isSafeInteger(value) || (value as number) < 0) throw new RangeError(`${label} must be non-negative`); }
function positive(value: unknown, label: string): void { if (!Number.isSafeInteger(value) || (value as number) <= 0) throw new RangeError(`${label} must be positive`); }
function json<T>(value: unknown): T { return typeof value === "string" ? JSON.parse(value) as T : clone(value as T); }
function ts(value: string, label: string): void { parseUtcTimestamp(value, label); }
function rowEvent(row: Record<string, unknown>): EventRecord { return json<EventRecord>(row.event ?? row); }

export class PostgresRuntimeState implements ProjectionCheckpointStore, ProjectionFailureStore, DeliveryStateStore, SubscriptionStore, OutboxStore, WorkerLeaseStore {
  readonly manifest = clone(manifest);
  private tenantContext: string | undefined;
  constructor(private readonly sessionFactory: (tenantId: string) => PgTenantSession, tenantId?: string) { if (tenantId !== undefined) identity(tenantId, "tenantId"); this.tenantContext = tenantId; }
  private tenant(): string { if (this.tenantContext === undefined) throw new Error("tenant context is required"); return this.tenantContext; }
  private bind(tenantId: string): void { identity(tenantId, "tenantId"); if (this.tenantContext === undefined) this.tenantContext = tenantId; if (this.tenantContext !== tenantId) throw new Error("tenant context mismatch"); }
  private run<T>(operation: (client: PgClient) => Promise<T>, tenantId = this.tenant()): Promise<T> { return this.sessionFactory(tenantId).withTransaction(operation); }

  async loadProjectionCheckpoint(projectorId: string, partitionId: string): Promise<number> { const tenant = this.tenant(); identity(projectorId, "projectorId"); identity(partitionId, "partitionId"); return this.run(async (c) => { const r = await c.query<{ position: number | string }>("SELECT position FROM work_fabric_projection_checkpoints WHERE tenant_id=$1 AND projector_id=$2 AND partition_id=$3", [tenant, projectorId, partitionId]); return Number(r.rows[0]?.position ?? 0); }); }
  async advanceProjectionCheckpoint(projectorId: string, partitionId: string, expectedPosition: number, newPosition: number): Promise<boolean> { const tenant = this.tenant(); nonNegative(expectedPosition, "expectedPosition"); nonNegative(newPosition, "newPosition"); return this.run(async (c) => { const r = await c.query("INSERT INTO work_fabric_projection_checkpoints (tenant_id,projector_id,partition_id,position) VALUES ($1,$2,$3,$4) ON CONFLICT (tenant_id,projector_id,partition_id) DO UPDATE SET position=EXCLUDED.position WHERE work_fabric_projection_checkpoints.position=$5 AND EXCLUDED.position>=work_fabric_projection_checkpoints.position", [tenant, projectorId, partitionId, newPosition, expectedPosition]); return r.rowCount > 0; }); }
  async resetProjectionCheckpoint(projectorId: string, partitionId: string): Promise<void> { const tenant = this.tenant(); await this.run((c) => c.query("DELETE FROM work_fabric_projection_checkpoints WHERE tenant_id=$1 AND projector_id=$2 AND partition_id=$3", [tenant, projectorId, partitionId]).then(() => undefined)); }
  async putProjectionFailure(failure: ProjectionFailureRecord): Promise<void> { const tenant = this.tenant(); identity(failure.projector_id, "projectorId"); identity(failure.partition_id, "partitionId"); identity(failure.event_id, "eventId"); positive(failure.position, "position"); ts(failure.recorded_at, "recordedAt"); await this.run((c) => c.query("INSERT INTO work_fabric_projection_failures (tenant_id,projector_id,partition_id,event_id,position,reason,recorded_at) VALUES ($1,$2,$3,$4,$5,$6,$7) ON CONFLICT (tenant_id,projector_id,partition_id,event_id) DO UPDATE SET position=EXCLUDED.position,reason=EXCLUDED.reason,recorded_at=EXCLUDED.recorded_at", [tenant, failure.projector_id, failure.partition_id, failure.event_id, failure.position, failure.reason, failure.recorded_at]).then(() => undefined)); }
  async listProjectionFailures(projectorId: string, partitionId: string): Promise<readonly ProjectionFailureRecord[]> { const tenant = this.tenant(); return this.run(async (c) => { const r = await c.query<Record<string, unknown>>("SELECT projector_id,partition_id,event_id,position,reason,recorded_at FROM work_fabric_projection_failures WHERE tenant_id=$1 AND projector_id=$2 AND partition_id=$3 ORDER BY position,event_id", [tenant, projectorId, partitionId]); return r.rows.map((row) => ({ projector_id: String(row.projector_id), partition_id: String(row.partition_id), event_id: String(row.event_id), position: Number(row.position), reason: String(row.reason), recorded_at: String(row.recorded_at) })); }); }

  async getSubscription(subscriptionId: string): Promise<RuntimeSubscription | null> { const tenant = this.tenant(); return this.run(async (c) => { const r = await c.query<{ payload: unknown }>("SELECT payload FROM work_fabric_subscriptions WHERE tenant_id=$1 AND subscription_id=$2", [tenant, subscriptionId]); return r.rows[0] === undefined ? null : clone(json<RuntimeSubscription>(r.rows[0].payload)); }); }
  async listActiveSubscriptions(tenantId: string): Promise<readonly RuntimeSubscription[]> { this.bind(tenantId); return this.run(async (c) => { const r = await c.query<{ payload: unknown }>("SELECT payload FROM work_fabric_subscriptions WHERE tenant_id=$1 AND (payload->>'state')='active' ORDER BY subscription_id", [tenantId]); return r.rows.map((row) => clone(json<RuntimeSubscription>(row.payload))); }, tenantId); }
  async putSubscription(subscription: RuntimeSubscription): Promise<void> { this.bind(subscription.tenant_id); await this.run((c) => c.query("INSERT INTO work_fabric_subscriptions (tenant_id,subscription_id,payload) VALUES ($1,$2,$3::jsonb) ON CONFLICT (tenant_id,subscription_id) DO UPDATE SET payload=EXCLUDED.payload", [subscription.tenant_id, subscription.subscription_id, JSON.stringify(subscription)]).then(() => undefined), subscription.tenant_id); }

  async claim(request: OutboxClaim): Promise<readonly OutboxRecord[]> { this.bind(request.tenant_id); ts(request.now, "now"); positive(request.lease_seconds, "lease_seconds"); positive(request.limit, "limit"); return this.run(async (c) => { const r = await c.query<Record<string, unknown>>("SELECT * FROM work_fabric_outbox WHERE tenant_id=$1 AND partition_id=$2 AND (next_attempt_at IS NULL OR next_attempt_at <= $3) AND (lease_expires_at IS NULL OR lease_expires_at <= $3) ORDER BY position LIMIT $4 FOR UPDATE SKIP LOCKED", [request.tenant_id, request.partition_id, request.now, request.limit]); const expires = addUtcTimestampSeconds(request.now, request.lease_seconds); const rows: OutboxRecord[] = []; for (const row of r.rows) { const token = Number(row.fencing_token) + 1; await c.query("UPDATE work_fabric_outbox SET lease_owner=$1,lease_expires_at=$2,fencing_token=$3 WHERE tenant_id=$4 AND outbox_id=$5", [request.owner, expires, token, request.tenant_id, row.outbox_id]); rows.push({ outbox_id: String(row.outbox_id), tenant_id: request.tenant_id, partition_id: String(row.partition_id), position: Number(row.position), event: rowEvent(row), attempt: Number(row.attempt), next_attempt_at: row.next_attempt_at === null ? null : String(row.next_attempt_at), lease_owner: request.owner, lease_expires_at: expires, fencing_token: token }); } return clone(rows); }, request.tenant_id); }
  async markPublished(outboxId: string, owner: string, fencingToken: number): Promise<boolean> { const tenant = this.tenant(); positive(fencingToken, "fencingToken"); return this.run(async (c) => (await c.query("DELETE FROM work_fabric_outbox WHERE tenant_id=$1 AND outbox_id=$2 AND lease_owner=$3 AND fencing_token=$4", [tenant, outboxId, owner, fencingToken])).rowCount > 0); }
  async recordFailure(outboxId: string, owner: string, fencingToken: number, nextAttemptAt: string): Promise<boolean> { const tenant = this.tenant(); positive(fencingToken, "fencingToken"); ts(nextAttemptAt, "nextAttemptAt"); return this.run(async (c) => (await c.query("UPDATE work_fabric_outbox SET attempt=attempt+1,next_attempt_at=$1,lease_owner=NULL,lease_expires_at=NULL WHERE tenant_id=$2 AND outbox_id=$3 AND lease_owner=$4 AND fencing_token=$5", [nextAttemptAt, tenant, outboxId, owner, fencingToken])).rowCount > 0); }
  async listPending(tenantId: string, partitionId: string): Promise<readonly OutboxRecord[]> { this.bind(tenantId); return this.run(async (c) => { const r = await c.query<Record<string, unknown>>("SELECT * FROM work_fabric_outbox WHERE tenant_id=$1 AND partition_id=$2 ORDER BY position", [tenantId, partitionId]); return r.rows.map((row) => ({ outbox_id: String(row.outbox_id), tenant_id: tenantId, partition_id: String(row.partition_id), position: Number(row.position), event: rowEvent(row), attempt: Number(row.attempt), next_attempt_at: row.next_attempt_at === null ? null : String(row.next_attempt_at), lease_owner: row.lease_owner === null ? null : String(row.lease_owner), lease_expires_at: row.lease_expires_at === null ? null : String(row.lease_expires_at), fencing_token: Number(row.fencing_token) })); }, tenantId); }

  async acquire(leaseKey: string, owner: string, now: string, leaseSeconds: number): Promise<WorkerLease | null> { const tenant = this.tenant(); ts(now, "now"); positive(leaseSeconds, "leaseSeconds"); return this.run(async (c) => { const r = await c.query<Record<string, unknown>>("INSERT INTO work_fabric_worker_leases (tenant_id,lease_key,owner,fencing_token,expires_at) VALUES ($1,$2,$3,1,$4) ON CONFLICT (tenant_id,lease_key) DO UPDATE SET owner=EXCLUDED.owner,fencing_token=work_fabric_worker_leases.fencing_token+1,expires_at=EXCLUDED.expires_at WHERE work_fabric_worker_leases.expires_at <= $5 RETURNING lease_key,owner,fencing_token,expires_at", [tenant, leaseKey, owner, addUtcTimestampSeconds(now, leaseSeconds), now]); const row = r.rows[0]; return row === undefined ? null : { lease_key: String(row.lease_key), owner: String(row.owner), fencing_token: Number(row.fencing_token), expires_at: String(row.expires_at) }; }); }
  async renew(leaseKey: string, owner: string, fencingToken: number, now: string, leaseSeconds: number): Promise<boolean> { const tenant = this.tenant(); ts(now, "now"); positive(fencingToken, "fencingToken"); positive(leaseSeconds, "leaseSeconds"); return this.run(async (c) => (await c.query("UPDATE work_fabric_worker_leases SET expires_at=$1 WHERE tenant_id=$2 AND lease_key=$3 AND owner=$4 AND fencing_token=$5", [addUtcTimestampSeconds(now, leaseSeconds), tenant, leaseKey, owner, fencingToken])).rowCount > 0); }
  async release(leaseKey: string, owner: string, fencingToken: number): Promise<boolean> { const tenant = this.tenant(); positive(fencingToken, "fencingToken"); return this.run(async (c) => (await c.query("DELETE FROM work_fabric_worker_leases WHERE tenant_id=$1 AND lease_key=$2 AND owner=$3 AND fencing_token=$4", [tenant, leaseKey, owner, fencingToken])).rowCount > 0); }

  async loadDeliveryPosition(subscriptionId: string, partitionId: string): Promise<number> { const tenant = this.tenant(); return this.run(async (c) => { const r = await c.query<{ position: number | string }>("SELECT position FROM work_fabric_delivery_positions WHERE tenant_id=$1 AND subscription_id=$2 AND partition_id=$3", [tenant, subscriptionId, partitionId]); return Number(r.rows[0]?.position ?? 0); }); }
  async recordDeliveryAttempt(attempt: DeliveryAttempt): Promise<void> { const tenant = this.tenant(); await this.run((c) => c.query("INSERT INTO work_fabric_delivery_attempts (tenant_id,subscription_id,partition_id,event_id,attempt,attempted_at,outcome,detail,next_attempt_at) VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9) ON CONFLICT DO NOTHING", [tenant, attempt.subscription_id, attempt.partition_id, attempt.event_id, attempt.attempt, attempt.attempted_at, attempt.outcome, attempt.detail, attempt.next_attempt_at]).then(() => undefined)); }
  async listDeliveryAttempts(subscriptionId: string, eventId: string): Promise<readonly DeliveryAttempt[]> { const tenant = this.tenant(); return this.run(async (c) => { const r = await c.query<Record<string, unknown>>("SELECT subscription_id,partition_id,event_id,attempt,attempted_at,outcome,detail,next_attempt_at FROM work_fabric_delivery_attempts WHERE tenant_id=$1 AND subscription_id=$2 AND event_id=$3 ORDER BY attempt", [tenant, subscriptionId, eventId]); return r.rows.map((row) => ({ subscription_id: String(row.subscription_id), partition_id: String(row.partition_id), event_id: String(row.event_id), attempt: Number(row.attempt), attempted_at: String(row.attempted_at), outcome: row.outcome as DeliveryAttempt["outcome"], detail: row.detail === null ? null : String(row.detail), next_attempt_at: row.next_attempt_at === null ? null : String(row.next_attempt_at) })); }); }
  async advanceDeliveryPosition(subscriptionId: string, partitionId: string, expectedPosition: number, newPosition: number): Promise<boolean> { const tenant = this.tenant(); nonNegative(expectedPosition, "expectedPosition"); nonNegative(newPosition, "newPosition"); return this.run(async (c) => (await c.query("INSERT INTO work_fabric_delivery_positions (tenant_id,subscription_id,partition_id,position) VALUES ($1,$2,$3,$4) ON CONFLICT (tenant_id,subscription_id,partition_id) DO UPDATE SET position=EXCLUDED.position WHERE work_fabric_delivery_positions.position=$5 AND EXCLUDED.position>=work_fabric_delivery_positions.position", [tenant, subscriptionId, partitionId, newPosition, expectedPosition])).rowCount > 0); }
  async putDeadLetter(record: DeadLetterRecord): Promise<void> { const tenant = this.tenant(); await this.run((c) => c.query("INSERT INTO work_fabric_dead_letters (tenant_id,subscription_id,event_id,payload,attempts,reason,recorded_at) VALUES ($1,$2,$3,$4::jsonb,$5,$6,$7) ON CONFLICT DO NOTHING", [tenant, record.subscription_id, record.event.event_id, JSON.stringify(record.event), record.attempts, record.reason, record.recorded_at]).then(() => undefined)); }
  async listDeadLetters(subscriptionId: string, eventId?: string): Promise<readonly DeadLetterRecord[]> { const tenant = this.tenant(); return this.run(async (c) => { const r = await c.query<Record<string, unknown>>("SELECT payload,attempts,reason,recorded_at,subscription_id FROM work_fabric_dead_letters WHERE tenant_id=$1 AND subscription_id=$2 AND ($3::text IS NULL OR event_id=$3) ORDER BY recorded_at,event_id", [tenant, subscriptionId, eventId ?? null]); return r.rows.map((row) => ({ subscription_id: String(row.subscription_id), event: json<EventRecord>(row.payload), attempts: Number(row.attempts), reason: String(row.reason), recorded_at: String(row.recorded_at) })); }); }
  async getActiveDelivery(subscriptionId: string, partitionId: string): Promise<PendingDeliveryRecord | null> { const tenant = this.tenant(); return this.run(async (c) => { const r = await c.query<Record<string, unknown>>("SELECT * FROM work_fabric_deliveries WHERE tenant_id=$1 AND subscription_id=$2 AND partition_id=$3 AND outcome='pending'", [tenant, subscriptionId, partitionId]); return r.rows[0] === undefined ? null : this.delivery(r.rows[0]); }); }
  private delivery(row: Record<string, unknown>): PendingDeliveryRecord { return { delivery_id: String(row.delivery_id), subscription_id: String(row.subscription_id), partition_id: String(row.partition_id), from_position: Number(row.from_position), to_position: Number(row.to_position), next_cursor: String(row.next_cursor), events: json<readonly EventRecord[]>(row.events), attempt: Number(row.attempt), delivered_at: String(row.delivered_at), visibility_expires_at: String(row.visibility_expires_at), outcome: row.outcome as PendingDeliveryRecord["outcome"] }; }
  async claimPendingDelivery(delivery: PendingDeliveryRecord, expectedActiveDeliveryId: string | null): Promise<DeliveryClaimResult> { const tenant = this.tenant(); const result = await this.run(async (c) => { const active = await c.query<Record<string, unknown>>("SELECT * FROM work_fabric_deliveries WHERE tenant_id=$1 AND subscription_id=$2 AND partition_id=$3 AND outcome='pending' FOR UPDATE", [tenant, delivery.subscription_id, delivery.partition_id]); const existing = active.rows[0]; if ((existing === undefined ? null : String(existing.delivery_id)) !== expectedActiveDeliveryId) return existing === undefined ? { kind: "claimed", delivery } as DeliveryClaimResult : { kind: "conflict", delivery: this.delivery(existing) } as DeliveryClaimResult; await c.query("INSERT INTO work_fabric_deliveries (tenant_id,delivery_id,subscription_id,partition_id,from_position,to_position,next_cursor,events,attempt,delivered_at,visibility_expires_at,outcome) VALUES ($1,$2,$3,$4,$5,$6,$7,$8::jsonb,$9,$10,$11,$12)", [tenant, delivery.delivery_id, delivery.subscription_id, delivery.partition_id, delivery.from_position, delivery.to_position, delivery.next_cursor, JSON.stringify(delivery.events), delivery.attempt, delivery.delivered_at, delivery.visibility_expires_at, delivery.outcome]); return { kind: "claimed" as const, delivery }; }); return clone(result); }
  async getDelivery(deliveryId: string): Promise<PendingDeliveryRecord | null> { const tenant = this.tenant(); return this.run(async (c) => { const r = await c.query<Record<string, unknown>>("SELECT * FROM work_fabric_deliveries WHERE tenant_id=$1 AND delivery_id=$2", [tenant, deliveryId]); return r.rows[0] === undefined ? null : this.delivery(r.rows[0]); }); }
  async settleDelivery(deliveryId: string, expectedOutcome: "pending", settlement: DeliverySettlement): Promise<DeliverySettlementResult> { const tenant = this.tenant(); return this.run(async (c) => { const r = await c.query<Record<string, unknown>>("UPDATE work_fabric_deliveries SET outcome=$1 WHERE tenant_id=$2 AND delivery_id=$3 AND outcome=$4 RETURNING *", [settlement.outcome, tenant, deliveryId, expectedOutcome]); if (r.rows[0] !== undefined) return { kind: "completed", delivery: this.delivery(r.rows[0]) }; const current = await c.query<Record<string, unknown>>("SELECT * FROM work_fabric_deliveries WHERE tenant_id=$1 AND delivery_id=$2", [tenant, deliveryId]); if (current.rows[0] === undefined) throw new Error("delivery not found"); return { kind: "conflict", delivery: this.delivery(current.rows[0]) }; }); }
}
